server:
  port: 9080
  
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2-console   
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: 
#    driverClassName: org.h2.Driver
      
mybatis:
  mapper-locations: classpath*:mapper/*.xml
